### ISSUE TITLE
Upgrade to NH5 etc

### ISSUE THREAD

**Issue by igitur** [andersthorsen/NHibernate.Property.Expression#1]
Hi,

Found this via your blog post from a few years ago. Looks like a brilliant extension to NH. Hope it will solve my issues with calculated properties.

With the last commit being 4 years ago, this doesn't work with NH5. I'm prepared to submit some PRs. Would also like to get this working on .NET Core. Just checking in with you first that you're willing to review the PRs and maybe help with some compatibility issues, as I'm not an expression with expressions and query providers. But I'll attempt the bulk of the effort. I'll also assist in getting this on NuGet if that's OK with you.

Let me know if you're OK with this.

thanks

**Comment by andersthorsen** [comment]
Go ahead if you have time.

I haven't touched NHibernate in a few years so my knowledge is most likely a bit rusty.
